import React, { useMemo } from 'react';
import { MODELS } from './ModelsPopup';

// Use import.meta.glob to efficiently find all GLB and PNG files in layouts
const layoutModelsGlob = import.meta.glob('../../assets/layouts/**/*.glb', { eager: true, import: 'default' });
const layoutImagesGlob = import.meta.glob('../../assets/layouts/**/*.png', { eager: true, import: 'default' });

const LAYOUT_MAPPING = {
  'beverage-cup': 'Carton Boxes/Beverage Bottle',
  'die-cut-box': 'Carton Boxes/Die Cut',
  'folding-box': 'Carton Boxes/Folding',
  'glass-bottle': 'Drinkware bottles/Glass bottle',
  'plastic-water-bottle': 'Drinkware bottles/Plastic Bottle',
  'soft-drinks-bottle': 'Drinkware bottles/soft drinks',
  'biodegradable-bags': 'Eco friendly/Bio degradable',
  'paper-bag': 'Eco friendly/Paper Bag',
  't-shirt': 'Fashion wear/T shirt',
  'hoodie': 'Fashion wear/Hoodie',
  'oval-container': 'Food Container/Oval',
  'round-container': 'Food Container/Round',
  'tamper-evident': 'Food Container/TE',
  'kraft-paper': 'Food Packaging/Kraft Paper',
  'zip-lock-pouches': 'Food Packaging/Zip lock',
  'box-sealing-tape': 'Packaging tapes/Sealing tapes'
};

export default function LayoutPopup({ currentModelUrl, onSelectLayout }) {
  // Find the currently selected model by matching URL or checking if it's already a layout
  // We check if currentModelUrl matches a base model URL or any layout inside a known folder
  const currentModel = useMemo(() => {
    // Exact match in base models
    let found = MODELS.find(m => m.modelUrl === currentModelUrl);
    if (found) return found;

    // If the user selected a layout, we need to find which base model it belongs to
    // We can infer it by checking if currentModelUrl exists in our layout mappings
    // Wait, the URLs generated by Vite might be completely hashed (e.g. /assets/xyz.glb)
    // Actually, Vite `?url` gives hashed URLs, but since we use `eager: true, import: 'default'`, 
    // `layoutModelsGlob` gives us the same hashed URLs. Let's find the matching layout path.
    const layoutPath = Object.keys(layoutModelsGlob).find(p => layoutModelsGlob[p] === currentModelUrl);
    if (layoutPath) {
       const mappedEntry = Object.entries(LAYOUT_MAPPING).find(([id, path]) => layoutPath.includes(path));
       if (mappedEntry) {
          return MODELS.find(m => m.id === mappedEntry[0]);
       }
    }
    return MODELS[0]; // fallback
  }, [currentModelUrl]);

  // Extract available layouts for this model
  const availableLayouts = useMemo(() => {
    if (!currentModel || !LAYOUT_MAPPING[currentModel.id]) return [];
    const prefix = `../../assets/layouts/${LAYOUT_MAPPING[currentModel.id]}/`;
    
    // Find all model paths that start with this prefix
    const modelPaths = Object.keys(layoutModelsGlob).filter(p => p.startsWith(prefix));
    
    return modelPaths.map((modelPath, index) => {
      const baseName = modelPath.substring(modelPath.lastIndexOf('/') + 1).replace(/\.glb$/, '');
      const imagePath = modelPath.replace(/\.glb$/, '.png');
      
      let imageUrl = layoutImagesGlob[imagePath];
      // Fallback fuzzy match for spaces issues (like "Bio de A- 4.png" vs "Bio de A-4.glb")
      if (!imageUrl) {
         const cleanBase = baseName.replace(/\s+/g, '');
         const fuzzyPath = Object.keys(layoutImagesGlob).find(p => 
            p.startsWith(prefix) && p.replace(/\s+/g, '').includes(cleanBase)
         );
         if (fuzzyPath) imageUrl = layoutImagesGlob[fuzzyPath];
      }

      return {
        id: `layout-${index + 1}`,
        name: `Layout ${index + 1}`,
        modelUrl: layoutModelsGlob[modelPath],
        imageUrl: imageUrl || null
      };
    });
  }, [currentModel]);

  return (
    <div className="w-[350px] h-fit max-h-[620px] shrink-0 bg-white rounded-[15px] shadow-[0_8px_30px_rgb(0,0,0,0.08)] overflow-hidden flex flex-col">
      <div className="p-5 pb-3 flex justify-between items-center">
        <h2 className="text-xl font-bold text-gray-900 m-0">Layouts</h2>
        <span className="text-xs bg-gray-100 text-gray-500 px-2 py-1 rounded-md font-semibold">
          {availableLayouts.length} available
        </span>
      </div>

      <div className="px-5 pb-5 overflow-y-auto flex-1 scrollbar-hide">
        {availableLayouts.length === 0 ? (
          <div className="text-center text-gray-400 py-8 text-sm">
            No layouts available for this model.
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-3">
            {availableLayouts.map((layout) => {
              const isActive = layout.modelUrl === currentModelUrl;
              return (
                <button
                  key={layout.id}
                  type="button"
                  onClick={() => onSelectLayout(layout.modelUrl)}
                  className={`relative aspect-[1.2] overflow-hidden rounded-lg border-2 bg-gray-50 p-1 cursor-pointer transition-all hover:border-[#c05520] hover:shadow-sm flex flex-col items-center justify-center gap-1.5 ${
                    isActive ? 'border-[#c05520] shadow-[0_0_0_2px_rgba(192,85,32,0.18)]' : 'border-gray-200'
                  }`}
                >
                  <div className="w-full h-full rounded border border-gray-100 bg-white flex items-center justify-center overflow-hidden">
                    {layout.imageUrl ? (
                      <img src={layout.imageUrl} alt={layout.name} className="w-full h-full object-cover" />
                    ) : (
                      <span className="text-[10px] text-gray-400">No Preview</span>
                    )}
                  </div>
                  {isActive && (
                    <div className="absolute top-1 right-1 w-4 h-4 bg-[#c05520] rounded-full flex items-center justify-center shadow-md">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="white" className="w-2.5 h-2.5">
                        <path fillRule="evenodd" d="M16.704 4.153a.75.75 0 0 1 .143 1.052l-8 10.5a.75.75 0 0 1-1.127.075l-4.5-4.5a.75.75 0 0 1 1.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 0 1 1.05-.143Z" clipRule="evenodd" />
                      </svg>
                    </div>
                  )}
                </button>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
